import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { ApiService } from '../../core/api/api.service';
interface Lead{id:string;name:string;company_name?:string;email?:string;phone?:string;stage:string;source?:string;estimated_value?:string;currency_code?:string}
@Component({selector:'app-crm-leads',imports:[ReactiveFormsModule],template:`
<div class="page-head"><div><h1>CRM · Leads</h1><p>Track prospects and convert qualified leads into customers.</p></div></div>
@if(success()){<div class="success">{{success()}}</div>}@if(error()){<div class="error">{{error()}}</div>}
<div class="grid crm-grid"><form class="card form-card" [formGroup]="form" (ngSubmit)="create()"><h3>Create lead</h3><label>Name<input formControlName="name">@if(form.controls.name.touched&&form.controls.name.invalid){<small class="field-error">Name is required.</small>}</label><label>Company<input formControlName="company_name"></label><label>Email<input type="email" formControlName="email"></label><label>Phone<input formControlName="phone"></label><label>Stage<select formControlName="stage"><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="proposal">Proposal</option><option value="won">Won</option><option value="lost">Lost</option></select></label><label>Source<input formControlName="source"></label><label>Estimated value<input type="number" min="0" formControlName="estimated_value"></label><label>Currency<input maxlength="3" formControlName="currency_code" placeholder="EUR"></label><button class="primary" [disabled]="submitting()">{{submitting()?'Creating...':'Create lead'}}</button></form><div class="card"><table><thead><tr><th>Name</th><th>Company</th><th>Stage</th><th>Value</th><th></th></tr></thead><tbody>@for(lead of leads();track lead.id){<tr><td>{{lead.name}}</td><td>{{lead.company_name||'-'}}</td><td><span class="badge">{{lead.stage}}</span></td><td>{{lead.estimated_value||'-'}} {{lead.currency_code||''}}</td><td>@if(lead.stage!=='won'&&lead.stage!=='lost'){<button (click)="convert(lead)">Convert</button>}</td></tr>}@empty{<tr><td colspan="5">No leads yet.</td></tr>}</tbody></table></div></div>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class LeadsComponent implements OnInit{readonly leads=signal<Lead[]>([]);readonly error=signal('');readonly success=signal('');readonly submitting=signal(false);readonly form=new FormGroup({name:new FormControl('',{nonNullable:true,validators:[Validators.required]}),company_name:new FormControl('',{nonNullable:true}),email:new FormControl('',{nonNullable:true,validators:[Validators.email]}),phone:new FormControl('',{nonNullable:true}),stage:new FormControl('new',{nonNullable:true}),source:new FormControl('',{nonNullable:true}),estimated_value:new FormControl<number|null>(null),currency_code:new FormControl('',{nonNullable:true})});constructor(private api:ApiService){}ngOnInit(){this.load();}load(){this.api.get<{data:Lead[]}>('/crm/leads').subscribe({next:r=>this.leads.set(r.data),error:e=>this.error.set(this.msg(e))});}create(){this.error.set('');this.success.set('');if(this.form.invalid){this.form.markAllAsTouched();this.error.set('Please correct the highlighted fields.');return;}this.submitting.set(true);const raw=this.form.getRawValue();this.api.post('/crm/leads',{...raw,company_name:raw.company_name||null,email:raw.email||null,phone:raw.phone||null,source:raw.source||null,currency_code:raw.currency_code?raw.currency_code.toUpperCase():null}).subscribe({next:()=>{this.success.set('Lead created successfully.');this.form.reset({name:'',company_name:'',email:'',phone:'',stage:'new',source:'',estimated_value:null,currency_code:''});this.submitting.set(false);this.load();},error:e=>{this.error.set(this.msg(e));this.submitting.set(false);}});}convert(lead:Lead){this.error.set('');this.api.post(`/crm/leads/${lead.id}/convert`,{}).subscribe({next:()=>{this.success.set('Lead converted to customer.');this.load();},error:e=>this.error.set(this.msg(e))});}private msg(e:HttpErrorResponse){const validation=e.error?.errors?Object.values(e.error.errors).flat().join(' '):'';return validation||e.error?.message||'Request failed.';}}
