import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { ApiService } from '../../core/api/api.service';
import { PlatformAuthService } from '../../core/auth/platform-auth.service';
interface Tenant{id:string;slug:string;status:string;timezone:string;organization?:{display_name:string;email?:string}}
@Component({selector:'app-platform-tenants',imports:[ReactiveFormsModule],template:`
<div class="platform-wrap"><header class="topbar"><strong>Super Admin · <a href="/platform/plans" style="color:inherit">Plans</a></strong><button (click)="auth.logout().subscribe()">Logout</button></header><main class="content">
<div class="page-head"><div><h1>Companies / Tenants</h1><p>Create and manage isolated SaaS workspaces.</p></div></div>
@if(success()){<div class="success">{{success()}}</div>}@if(error()){<div class="error">{{error()}}</div>}
<div class="grid platform-grid"><form class="card login-card" [formGroup]="form" (ngSubmit)="create()"><h3>Create tenant</h3>
<label>Workspace slug<input formControlName="slug" (blur)="form.controls.slug.markAsTouched()">@if(form.controls.slug.touched&&form.controls.slug.invalid){<small class="field-error">Workspace slug is required.</small>}</label>
<label>Legal name<input formControlName="legal_name" (blur)="form.controls.legal_name.markAsTouched()">@if(form.controls.legal_name.touched&&form.controls.legal_name.invalid){<small class="field-error">Legal name is required.</small>}</label>
<label>Display name<input formControlName="display_name" (blur)="form.controls.display_name.markAsTouched()">@if(form.controls.display_name.touched&&form.controls.display_name.invalid){<small class="field-error">Display name is required.</small>}</label>
<label>Company email<input formControlName="organization_email" type="email" (blur)="form.controls.organization_email.markAsTouched()">@if(form.controls.organization_email.touched&&form.controls.organization_email.invalid){<small class="field-error">Enter a valid company email.</small>}</label>
<label>Owner name<input formControlName="owner_name" (blur)="form.controls.owner_name.markAsTouched()">@if(form.controls.owner_name.touched&&form.controls.owner_name.invalid){<small class="field-error">Owner name is required.</small>}</label>
<label>Owner email<input formControlName="owner_email" type="email" (blur)="form.controls.owner_email.markAsTouched()">@if(form.controls.owner_email.touched&&form.controls.owner_email.invalid){<small class="field-error">Enter a valid owner email.</small>}</label>
<label>Owner password<input formControlName="owner_password" type="password" (blur)="form.controls.owner_password.markAsTouched()">@if(form.controls.owner_password.touched&&form.controls.owner_password.hasError('minlength')){<small class="field-error">Password must be at least 12 characters.</small>}@if(form.controls.owner_password.touched&&form.controls.owner_password.hasError('required')){<small class="field-error">Owner password is required.</small>}</label>
<button class="primary" type="submit" [disabled]="submitting()">{{submitting()?'Creating...':'Create company'}}</button></form>
<div class="card"><table><thead><tr><th>Company</th><th>Workspace</th><th>Status</th></tr></thead><tbody>@for(t of tenants();track t.id){<tr><td>{{t.organization?.display_name||'-'}}</td><td>{{t.slug}}</td><td>{{t.status}}</td></tr>}@empty{<tr><td colspan="3">No tenants yet.</td></tr>}</tbody></table></div></div></main></div>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class PlatformTenantsComponent implements OnInit{readonly tenants=signal<Tenant[]>([]);readonly error=signal('');readonly success=signal('');readonly submitting=signal(false);readonly form=new FormGroup({slug:new FormControl('',{nonNullable:true,validators:[Validators.required]}),legal_name:new FormControl('',{nonNullable:true,validators:[Validators.required]}),display_name:new FormControl('',{nonNullable:true,validators:[Validators.required]}),organization_email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),owner_name:new FormControl('',{nonNullable:true,validators:[Validators.required]}),owner_email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),owner_password:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(12)]})});constructor(private api:ApiService,public auth:PlatformAuthService){}ngOnInit(){this.auth.loadMe().subscribe();this.load();}load(){this.api.get<{data:Tenant[]}>('/platform/tenants').subscribe(r=>this.tenants.set(r.data));}create(){this.error.set('');this.success.set('');if(this.form.invalid){this.form.markAllAsTouched();this.error.set('Please correct the highlighted fields.');return;}this.submitting.set(true);this.api.post('/platform/tenants',this.form.getRawValue()).subscribe({next:()=>{this.form.reset();this.success.set('Company created successfully.');this.submitting.set(false);this.load();},error:(e:HttpErrorResponse)=>{const validation=e.error?.errors?Object.values(e.error.errors).flat().join(' '):'';this.error.set(validation||e.error?.message||'Could not create company.');this.submitting.set(false);}});}}
